### ISSUE TITLE
New models onto kv260

### ISSUE THREAD

**Issue by ombhilare999** [Xilinx/kv260-firmware#1]
Can we add new models on kv260?
are there any tutorial for this, thank you.

**Comment by xlnx-yuxiz** [comment]
@ombhilare999 As mentioned in https://xilinx.github.io/kria-apps-docs/main/build/html/docs/smartcamera/docs/hw_arch_accel.html, we use DPU B3136 in our pre-released design, so you can compile those models supported by Vitis AI for DPU B3136 or deploy your own caffe/tensorflow/pytorch model from the very start, for detailed info please refer to the [Vitis AI User Guide](https://www.xilinx.com/support/documentation/sw_manuals/vitis_ai/1_4/ug1414-vitis-ai.pdf).

 Kv260 also has related pages for how to customize the models used in our released application: [smartcam](https://xilinx.github.io/kria-apps-docs/main/build/html/docs/smartcamera/docs/customize_ai_models.html) and [aibox-reid](https://xilinx.github.io/kria-apps-docs/main/build/html/docs/aibox-reid/docs/customize_ai_models-aib.html).

**Comment by chkohn** [comment]
closing this issue per comment from @xlnx-yuxiz
